name: Manual Image Processing and Deployment

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/images/*"
      - "src/images/portfolio/*"
    branches:
      - staging

jobs:
  filter-paths:
    runs-on: ubuntu-latest
    outputs:
      root-changed: ${{ steps.filter.outputs.root }}
      portfolio-changed: ${{ steps.filter.outputs.portfolio }}
      manual-trigger: ${{ github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            root:
              - 'src/images/*'
            portfolio:
              - 'src/images/portfolio/*'

  process-root-images:
    runs-on: ubuntu-latest
    needs: filter-paths
    if: needs.filter-paths.outputs.root-changed == 'true' || needs.filter-paths.outputs.manual-trigger == 'true'

    steps:
      - name: Determine branch name
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up webp tools
        run: sudo apt-get install -y webp

      - name: Process root images
        run: |
          mkdir -p public/images
          for file in $(find ./src/images -maxdepth 1 -type f -name '*.webp'); do
            filename=$(basename -- "$file")
            # Check if the filename contains a locale suffix
            if [[ "$filename" =~ -fr\.webp$ ]] || [[ "$filename" =~ -en\.webp$ ]] || [[ "$filename" =~ -cn\.webp$ ]]; then
              # Process images with locale
              basename=$(echo "$filename" | sed -E 's/-(fr|en|cn)\.webp$//')
              locale=$(echo "$filename" | sed -E 's/^.*-(fr|en|cn)\.webp$/\1/')
              cwebp -q 82 "$file" -resize 320 0 -o "public/images/${basename}-${locale}-320.webp"
              cwebp -q 82 "$file" -resize 640 0 -o "public/images/${basename}-${locale}-640.webp"
              cwebp -q 82 "$file" -resize 1280 0 -o "public/images/${basename}-${locale}-1280.webp"
              cwebp -q 85 "$file" -resize 1920 0 -o "public/images/${basename}-${locale}-1920.webp"
              cwebp -q 90 "$file" -resize 2560 0 -o "public/images/${basename}-${locale}-2560.webp"
            else
              # Process images without locale for all locales
              basename="${filename%.*}"
              for locale in fr en cn; do
                cwebp -q 82 "$file" -resize 320 0 -o "public/images/${basename}-${locale}-320.webp"
                cwebp -q 82 "$file" -resize 640 0 -o "public/images/${basename}-${locale}-640.webp"
                cwebp -q 82 "$file" -resize 1280 0 -o "public/images/${basename}-${locale}-1280.webp"
                cwebp -q 85 "$file" -resize 1920 0 -o "public/images/${basename}-${locale}-1920.webp"
                cwebp -q 90 "$file" -resize 2560 0 -o "public/images/${basename}-${locale}-2560.webp"
              done
            fi
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/images/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "images(Github Actions) add or update resized images from /src/images"
            git pull --ff-only origin ${{ env.BRANCH_NAME }}
            git push origin HEAD:${{ env.BRANCH_NAME }}
          fi

  process-portfolio-images:
    runs-on: ubuntu-latest
    needs: filter-paths
    if: needs.filter-paths.outputs.portfolio-changed == 'true' || needs.filter-paths.outputs.manual-trigger == 'true'

    steps:
      - name: Determine branch name
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up webp tools
        run: sudo apt-get install -y webp

      - name: Process portfolio images
        run: |
          mkdir -p public/images/portfolio
          for file in $(find ./src/images/portfolio -type f -name '*.webp'); do
            filename=$(basename -- "$file")
            # Check if the filename contains a locale suffix
            if [[ "$filename" =~ -fr\.webp$ ]] || [[ "$filename" =~ -en\.webp$ ]] || [[ "$filename" =~ -cn\.webp$ ]]; then
              # Process images with locale
              basename=$(echo "$filename" | sed -E 's/-(fr|en|cn)\.webp$//')
              locale=$(echo "$filename" | sed -E 's/^.*-(fr|en|cn)\.webp$/\1/')
              cwebp -q 70 "$file" -resize 320 0 -o "public/images/${basename}-${locale}-320.webp"
              cwebp -q 70 "$file" -resize 640 0 -o "public/images/${basename}-${locale}-640.webp"
              cwebp -q 70 "$file" -resize 1280 0 -o "public/images/${basename}-${locale}-1280.webp"
              cwebp -q 75 "$file" -resize 1920 0 -o "public/images/${basename}-${locale}-1920.webp"
              cwebp -q 80 "$file" -resize 2560 0 -o "public/images/${basename}-${locale}-2560.webp"
            else
              # Process images without locale for all locales
              basename="${filename%.*}"
              for locale in fr en cn; do
                cwebp -q 70 "$file" -resize 320 0 -o "public/images/${basename}-${locale}-320.webp"
                cwebp -q 70 "$file" -resize 640 0 -o "public/images/${basename}-${locale}-640.webp"
                cwebp -q 70 "$file" -resize 1280 0 -o "public/images/${basename}-${locale}-1280.webp"
                cwebp -q 75 "$file" -resize 1920 0 -o "public/images/${basename}-${locale}-1920.webp"
                cwebp -q 80 "$file" -resize 2560 0 -o "public/images/${basename}-${locale}-2560.webp"
              done
            fi
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/images/portfolio/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "images(Github Actions) add or update resized images from /src/images/portfolio"
            git pull --ff-only origin ${{ env.BRANCH_NAME }}
            git push origin HEAD:${{ env.BRANCH_NAME }}
          fi
